//API 1
//all todos
GET http://localhost:3000/todos/
//passing parameters status todo
###
GET http://localhost:3000/todos/?status=TO%20DO

//passing parameters priority high
###
GET http://localhost:3000/todos/?priority=HIGH
//passing parameters
###
GET http://localhost:3000/todos/?status=IN%20PROGRESS&priority=HIGH

//passing search_q
###
GET http://localhost:3000/todos/?search_q=Java


//API 2

###
GET http://localhost:3000/todos/2/

//API 3
###
POST http://localhost:3000/todos/
Content-Type:application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

//put todo
###

PUT http://localhost:3000/todos/2/
Content-Type:application/json

{"status": "DONE"}

###
PUT http://localhost:3000/todos/2/
Content-Type:application/json

{"priority": "HIGH"}

###
PUT http://localhost:3000/todos/2/
Content-Type:application/json

{"todo": "Some task"}

//delete todo
###
DELETE http://localhost:3000/todos/4/
